Feature/1078 extend provider loader with itemrunner
oat-sa/tao-test-runner-fe pull request #26
Opened 2020-06-02 09:29 UTC by btamas

Related to https://oat-sa.atlassian.net/browse/NEX-1078

- The nextgen testrunner configuration is provided by the deliver backend. This config contains provider list like test runner, communicator etc. The new UI test runner won't load the new UI item runner automatically, so it should be triggered. I created a new configuration key, called `itemRunner` and I extended the provider loader to be able to load it.
- I've mocked the item runner, so test runner still doesn't depend on item runner.
- I've written small test for the modifications.
- From now, the test runner configuration will contain HTMLElement container. https://github.com/oat-sa/tao-test-runner-fe/blob/fix/1078_extend-providerLoader-with-itemrunner/src/runnerComponent.js#L135
- I had to upgrade package versions, because there were a warning regarding outdated browserlist

- [ ] Do not forget to release it after merge

2020-06-03 13:26 UTC, krampstudio commented
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-06-03 13:57 UTC, krampstudio requested changes

2020-06-03 13:57 UTC, krampstudio commented on package.json
> +        "@oat-sa/browserslist-config-tao": "^0.1.1",
you need to add the dependency to `@oat-sa/tao-item-runner`

2020-06-03 13:57 UTC, krampstudio commented on src/runnerComponent.js
> +                renderTo: this.getElement().get(0)
it looks like there are still some external expectation for it to be a jquery element :/

2020-06-04 08:36 UTC, shaveko approved these changes
Code looks ok and test run doesn't return errors

2020-06-04 12:47 UTC, krampstudio approved these changes
Now previews are working as expected :+1:

2020-06-04 12:48 UTC, merged